version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: "/packages/vgplot/widget"
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: "/packages/server/duckdb-server"
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: "/packages/server/duckdb-server-rust"
    schedule:
      interval: monthly
