packages:
  - "packages/mosaic/*"
  - "packages/server/*"
  - "packages/vgplot/*"
  - "packages/examples/*"
allowBuilds:
  esbuild: false
  nx: false
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
