catalog:
  "@uwdata/flechette": ^2.6.0
packages:
  - "packages/mosaic/*"
  - "packages/server/*"
  - "packages/vgplot/*"
  - "packages/examples/*"
  - "conformance"
allowBuilds:
  esbuild: false
  nx: false
