[tool.uv.workspace]
members = [
    "packages/duckdb-server",
    "packages/widget"
]

# https://github.com/charliermarsh/ruff
[tool.ruff]
extend-include = ["*.ipynb"]

[tool.ruff.lint]
pydocstyle = { convention = "numpy" }
ignore = ["G004", "TRY301", "EM102", "EM101", "TRY003", "FBT002", "S608", "TRY002", "ARG001"]
