from .spec import meta, spec, Spec
from .data import parquet, csv, spatial, table, json, data
from .params import param, selection
from .encodings import (
    sql,
    count,
    sum,
    avg,
    mean,
    min,
    max,
    median,
    argmax,
    argmin,
    bin,
    date_month,
    date_month_day,
    centroid_x,
    centroid_y,
    column,
    geojson,
    channels,
)
from .plot import (
    plot,
    source,
    mark,
    directive,
    # ── Marks: original ──────────────────────────────────────────────────
    rule_y,
    rule_x,
    line_y,
    line_x,
    bar_y,
    bar_x,
    area_y,
    area_x,
    text,
    dot,
    density,
    # ── Marks: additional ────────────────────────────────────────────────
    area,
    arrow,
    axis_x,
    axis_y,
    axis_fx,
    axis_fy,
    cell,
    cell_x,
    cell_y,
    contour,
    voronoi,
    voronoi_mesh,
    delaunay_link,
    delaunay_mesh,
    hull,
    density_x,
    density_y,
    dense_line,
    dot_x,
    dot_y,
    circle,
    hexagon,
    frame,
    geo,
    sphere,
    graticule,
    grid_x,
    grid_y,
    grid_fx,
    grid_fy,
    hexgrid,
    heatmap,
    hexbin,
    image,
    line,
    regression_y,
    link,
    raster,
    rect,
    rect_x,
    rect_y,
    tick_x,
    tick_y,
    text_x,
    text_y,
    vector,
    vector_x,
    vector_y,
    spike,
    # ── Directives: original ─────────────────────────────────────────────
    y_grid,
    y_label,
    y_tick_format,
    x_tick_format,
    x_axis,
    y_axis,
    x_label,
    x_label_anchor,
    y_label_anchor,
    r_range,
    color_domain,
    color_scale,
    x_tick_size,
    y_tick_size,
    width,
    height,
    margins,
    # ── Directives: general plot ─────────────────────────────────────────
    name,
    style,
    margin,
    margin_left,
    margin_right,
    margin_top,
    margin_bottom,
    align,
    aspect_ratio,
    inset,
    axis,
    grid,
    label,
    padding,
    round,
    # ── Directives: x scale ──────────────────────────────────────────────
    x_scale,
    x_domain,
    x_range,
    x_nice,
    x_inset,
    x_inset_left,
    x_inset_right,
    x_clamp,
    x_round,
    x_align,
    x_padding,
    x_padding_inner,
    x_padding_outer,
    x_ticks,
    x_tick_spacing,
    x_tick_padding,
    x_tick_rotate,
    x_grid,
    x_line,
    x_label_offset,
    x_font_variant,
    x_aria_label,
    x_aria_description,
    x_reverse,
    x_zero,
    # ── Directives: y scale ──────────────────────────────────────────────
    y_scale,
    y_domain,
    y_range,
    y_nice,
    y_inset,
    y_inset_top,
    y_inset_bottom,
    y_clamp,
    y_round,
    y_align,
    y_padding,
    y_padding_inner,
    y_padding_outer,
    y_ticks,
    y_tick_spacing,
    y_tick_padding,
    y_tick_rotate,
    y_line,
    y_label_offset,
    y_font_variant,
    y_aria_label,
    y_aria_description,
    y_reverse,
    y_zero,
    # ── Directives: color scale ──────────────────────────────────────────
    color_range,
    color_clamp,
    color_nice,
    color_scheme,
    color_interpolate,
    color_pivot,
    color_symmetric,
    color_label,
    color_reverse,
    color_zero,
    color_tick_format,
    # ── Directives: opacity scale ────────────────────────────────────────
    opacity_scale,
    opacity_domain,
    opacity_range,
    opacity_clamp,
    opacity_nice,
    opacity_label,
    opacity_reverse,
    opacity_zero,
    opacity_tick_format,
    # ── Directives: r scale ──────────────────────────────────────────────
    r_scale,
    r_domain,
    r_clamp,
    r_nice,
    r_label,
    r_zero,
    # ── Directives: length scale ─────────────────────────────────────────
    length_scale,
    length_domain,
    length_range,
    length_clamp,
    length_nice,
    length_zero,
    # ── Directives: fx scale ─────────────────────────────────────────────
    fx_domain,
    fx_range,
    fx_inset,
    fx_inset_left,
    fx_inset_right,
    fx_round,
    fx_align,
    fx_padding,
    fx_padding_inner,
    fx_padding_outer,
    fx_axis,
    fx_tick_size,
    fx_tick_padding,
    fx_tick_format,
    fx_tick_rotate,
    fx_grid,
    fx_label,
    fx_label_anchor,
    fx_label_offset,
    fx_font_variant,
    fx_aria_label,
    fx_aria_description,
    fx_reverse,
    # ── Directives: fy scale ─────────────────────────────────────────────
    fy_domain,
    fy_range,
    fy_inset,
    fy_inset_top,
    fy_inset_bottom,
    fy_round,
    fy_align,
    fy_padding,
    fy_padding_inner,
    fy_padding_outer,
    fy_axis,
    fy_tick_size,
    fy_tick_padding,
    fy_tick_format,
    fy_tick_rotate,
    fy_grid,
    fy_label,
    fy_label_anchor,
    fy_label_offset,
    fy_font_variant,
    fy_aria_label,
    fy_aria_description,
    fy_reverse,
    # ── Directives: facet ────────────────────────────────────────────────
    facet_margin,
    facet_margin_top,
    facet_margin_bottom,
    facet_margin_left,
    facet_margin_right,
    facet_grid,
    facet_label,
    # ── Directives: projection ───────────────────────────────────────────
    projection_type,
    projection_parallels,
    projection_precision,
    projection_rotate,
    projection_domain,
    projection_inset,
    projection_inset_left,
    projection_inset_right,
    projection_inset_top,
    projection_inset_bottom,
    projection_clip,
    # ── Layout ───────────────────────────────────────────────────────────
    vconcat,
    hconcat,
    vspace,
    hspace,
    # ── Inputs ───────────────────────────────────────────────────────────
    slider,
    select,
    checkbox,
    menu,
    search,
    table_input,
    input,
    option,
    # ── Interactors ──────────────────────────────────────────────────────
    brush,
    sort,
    interval_x,
    interval_y,
    interval_xy,
    toggle,
    toggle_x,
    toggle_y,
    toggle_color,
    nearest_x,
    nearest_y,
    region,
    highlight,
    pan,
    pan_x,
    pan_y,
    pan_zoom,
    pan_zoom_x,
    pan_zoom_y,
    # ── Legends ──────────────────────────────────────────────────────────
    color_legend,
    opacity_legend,
    symbol_legend,
)

__all__ = [
    # spec
    "meta",
    "spec",
    "Spec",
    # data
    "parquet",
    "csv",
    "spatial",
    "table",
    "json",
    "data",
    # params
    "param",
    "selection",
    # plot core
    "plot",
    "source",
    "mark",
    "directive",
    # marks: original
    "rule_y",
    "rule_x",
    "line_y",
    "line_x",
    "bar_y",
    "bar_x",
    "area_y",
    "area_x",
    "text",
    "dot",
    "density",
    # marks: additional
    "area",
    "arrow",
    "axis_x",
    "axis_y",
    "axis_fx",
    "axis_fy",
    "cell",
    "cell_x",
    "cell_y",
    "contour",
    "voronoi",
    "voronoi_mesh",
    "delaunay_link",
    "delaunay_mesh",
    "hull",
    "density_x",
    "density_y",
    "dense_line",
    "dot_x",
    "dot_y",
    "circle",
    "hexagon",
    "frame",
    "geo",
    "sphere",
    "graticule",
    "grid_x",
    "grid_y",
    "grid_fx",
    "grid_fy",
    "hexgrid",
    "heatmap",
    "hexbin",
    "image",
    "line",
    "regression_y",
    "link",
    "raster",
    "rect",
    "rect_x",
    "rect_y",
    "tick_x",
    "tick_y",
    "text_x",
    "text_y",
    "vector",
    "vector_x",
    "vector_y",
    "spike",
    # directives: original
    "y_grid",
    "y_label",
    "y_tick_format",
    "x_tick_format",
    "x_axis",
    "y_axis",
    "x_label",
    "x_label_anchor",
    "y_label_anchor",
    "r_range",
    "color_domain",
    "color_scale",
    "x_tick_size",
    "y_tick_size",
    "width",
    "height",
    "margins",
    # directives: general plot
    "name",
    "style",
    "margin",
    "margin_left",
    "margin_right",
    "margin_top",
    "margin_bottom",
    "align",
    "aspect_ratio",
    "inset",
    "axis",
    "grid",
    "label",
    "padding",
    "round",
    # directives: x scale
    "x_scale",
    "x_domain",
    "x_range",
    "x_nice",
    "x_inset",
    "x_inset_left",
    "x_inset_right",
    "x_clamp",
    "x_round",
    "x_align",
    "x_padding",
    "x_padding_inner",
    "x_padding_outer",
    "x_ticks",
    "x_tick_spacing",
    "x_tick_padding",
    "x_tick_rotate",
    "x_grid",
    "x_line",
    "x_label_offset",
    "x_font_variant",
    "x_aria_label",
    "x_aria_description",
    "x_reverse",
    "x_zero",
    # directives: y scale
    "y_scale",
    "y_domain",
    "y_range",
    "y_nice",
    "y_inset",
    "y_inset_top",
    "y_inset_bottom",
    "y_clamp",
    "y_round",
    "y_align",
    "y_padding",
    "y_padding_inner",
    "y_padding_outer",
    "y_ticks",
    "y_tick_spacing",
    "y_tick_padding",
    "y_tick_rotate",
    "y_line",
    "y_label_offset",
    "y_font_variant",
    "y_aria_label",
    "y_aria_description",
    "y_reverse",
    "y_zero",
    # directives: color scale
    "color_range",
    "color_clamp",
    "color_nice",
    "color_scheme",
    "color_interpolate",
    "color_pivot",
    "color_symmetric",
    "color_label",
    "color_reverse",
    "color_zero",
    "color_tick_format",
    # directives: opacity scale
    "opacity_scale",
    "opacity_domain",
    "opacity_range",
    "opacity_clamp",
    "opacity_nice",
    "opacity_label",
    "opacity_reverse",
    "opacity_zero",
    "opacity_tick_format",
    # directives: r scale
    "r_scale",
    "r_domain",
    "r_clamp",
    "r_nice",
    "r_label",
    "r_zero",
    # directives: length scale
    "length_scale",
    "length_domain",
    "length_range",
    "length_clamp",
    "length_nice",
    "length_zero",
    # directives: fx scale
    "fx_domain",
    "fx_range",
    "fx_inset",
    "fx_inset_left",
    "fx_inset_right",
    "fx_round",
    "fx_align",
    "fx_padding",
    "fx_padding_inner",
    "fx_padding_outer",
    "fx_axis",
    "fx_tick_size",
    "fx_tick_padding",
    "fx_tick_format",
    "fx_tick_rotate",
    "fx_grid",
    "fx_label",
    "fx_label_anchor",
    "fx_label_offset",
    "fx_font_variant",
    "fx_aria_label",
    "fx_aria_description",
    "fx_reverse",
    # directives: fy scale
    "fy_domain",
    "fy_range",
    "fy_inset",
    "fy_inset_top",
    "fy_inset_bottom",
    "fy_round",
    "fy_align",
    "fy_padding",
    "fy_padding_inner",
    "fy_padding_outer",
    "fy_axis",
    "fy_tick_size",
    "fy_tick_padding",
    "fy_tick_format",
    "fy_tick_rotate",
    "fy_grid",
    "fy_label",
    "fy_label_anchor",
    "fy_label_offset",
    "fy_font_variant",
    "fy_aria_label",
    "fy_aria_description",
    "fy_reverse",
    # directives: facet
    "facet_margin",
    "facet_margin_top",
    "facet_margin_bottom",
    "facet_margin_left",
    "facet_margin_right",
    "facet_grid",
    "facet_label",
    # directives: projection
    "projection_type",
    "projection_parallels",
    "projection_precision",
    "projection_rotate",
    "projection_domain",
    "projection_inset",
    "projection_inset_left",
    "projection_inset_right",
    "projection_inset_top",
    "projection_inset_bottom",
    "projection_clip",
    # layout
    "vconcat",
    "hconcat",
    "vspace",
    "hspace",
    # inputs
    "slider",
    "select",
    "checkbox",
    "menu",
    "search",
    "table_input",
    "input",
    "option",
    # interactors
    "brush",
    "sort",
    "interval_x",
    "interval_y",
    "interval_xy",
    "toggle",
    "toggle_x",
    "toggle_y",
    "toggle_color",
    "nearest_x",
    "nearest_y",
    "region",
    "highlight",
    "pan",
    "pan_x",
    "pan_y",
    "pan_zoom",
    "pan_zoom_x",
    "pan_zoom_y",
    # legends
    "color_legend",
    "opacity_legend",
    "symbol_legend",
    # encodings
    "sql",
    "count",
    "sum",
    "avg",
    "mean",
    "min",
    "max",
    "median",
    "argmax",
    "argmin",
    "bin",
    "date_month",
    "date_month_day",
    "centroid_x",
    "centroid_y",
    "column",
    "geojson",
    "channels",
]


def __getattr__(name: str):
    """Dynamic mark/directive factory for names not explicitly exported.

    Allows any snake_case mark or directive to be used without an explicit
    function definition, e.g.::
    """
    if name.startswith("_"):
        raise AttributeError(name)

    from .plot import Directive, Mark
    from .util import camelize

    camel = camelize(name)

    def _factory(*args, data=None, **kwargs):
        if len(args) == 1 and data is None and not kwargs:
            # Single positional arg, no encodings: treat as a directive value.
            return Directive(camel, args[0])
        # Otherwise it is a mark; a leading positional arg is the data source.
        if args:
            if len(args) > 1:
                raise TypeError(
                    f"vg.{name}() takes at most one positional (data) argument"
                )
            if data is not None:
                raise TypeError(
                    f"vg.{name}() got data both positionally and by keyword"
                )
            data = args[0]
        return Mark(camel, data=data, enc=kwargs if kwargs else None)

    _factory.__name__ = name
    _factory.__qualname__ = f"vgplot.{name}"
    return _factory
