export const clickhouseExamples = [
  "aeromagnetic-survey",
  "airline-travelers",
  "area-sine",
  "athlete-birth-waffle",
  "athlete-height",
  "athletes",
  "axes",
  "bias",
  "contours",
  "crossfilter",
  "density-groups",
  "density1d",
  "density2d",
  "driving-shifts",
  "facet-interval",
  "flights-200k",
  "flights-density",
  "flights-hexbin",
  "legends",
  "line",
  "line-density",
  "line-multi-series",
  "linear-regression",
  "moving-average",
  "normalize",
  "overview-detail",
  "pan-zoom",
  "population-arrows",
  "protein-design",
  "seattle-temp",
  "sorted-bars",
  "splom",
  "symbols",
  "table",
  "triangle-wave",
  "voronoi",
  "weather",
  "wind-map",
  "wnba-shots",
];

export function clickhouseDatabase(name) {
  return `mosaic_demo_${name.replaceAll("-", "_")}`;
}
