[project]
name = "duckdb-server"
description = "A DuckDB server for Mosaic"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "diskcache",
  "duckdb>=1.3.1",
  "pandas",
  "pyarrow",
  "socketify",
  "ujson"
]

[project.scripts]
duckdb-server = "pkg.__main__:serve"

[project.urls]
homepage = "https://github.com/uwdata/mosaic"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "mypy",
  "pytest-cov",
  "pytest",
  "ruff",
  "types-ujson",
  "watchdog",
]

[tool.hatch.build.targets.wheel]
packages = ["pkg"]

[tool.hatch.version]
path = "package.json"
pattern = "\"version\": \"(?P<version>.+?)\""

# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
files = "pkg/**/*.py"
strict = false
ignore_missing_imports = true
