name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run docs:build

      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
